# Generated by Django 3.2.21 on 2023-10-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-updated', '-chat_count']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created', 'updated']},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
