# Generated by Django 3.2.21 on 2023-10-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20231003_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created', 'updated']},
        ),
    ]
